INSERT INTO Product (name, description, price, stock) VALUES
('Organic Cotton T-Shirt', 'A comfortable and sustainable t-shirt made from 100% organic cotton', 29.99, 50),
('Bluetooth Wireless Earbuds', 'High-quality wireless earbuds with noise-cancelling technology and long battery life', 149.99, 100),
('Smartphone Case', 'A stylish and durable case to protect your smartphone', 19.99, 200),
('Wooden Cutting Board', 'A handcrafted cutting board made from sustainably-sourced hardwood', 39.99, 25),
('Gourmet Coffee Blend', 'A rich and flavorful coffee blend made from high-quality beans', 12.99, 75),
('Fitness Tracker Watch', 'A high-tech watch that tracks your daily activity, heart rate, and sleep', 129.99, 50),
('Handmade Leather Wallet', 'A stylish and durable wallet made from genuine leather', 49.99, 75),
('Stainless Steel Water Bottle', 'A sleek and eco-friendly water bottle that keeps your drinks cold for hours', 24.99, 100),
('Natural Soy Wax Candle', 'A hand-poured candle made from 100% natural soy wax and essential oils', 19.99, 50),
('Wireless Charger Pad', 'A fast-charging wireless charger pad compatible with most smartphones', 29.99, 150),
('Portable Bluetooth Speaker', 'A compact and powerful wireless speaker with impressive sound quality', 99.99, 25),
('Linen Bed Sheets', 'A set of high-quality bed sheets made from 100% linen', 119.99, 50),
('Reusable Shopping Tote Bag', 'An eco-friendly and durable tote bag made from recycled materials', 9.99, 200),
('Handheld Milk Frother', 'A battery-operated milk frother for making delicious coffee drinks at home', 14.99, 100),
('Smart Thermostat', 'A programmable thermostat that learns your schedule and saves energy', 199.99, 20),
('Collapsible Travel Mug', 'A space-saving and eco-friendly travel mug that fits in your pocket', 14.99, 75),
('Natural Wood Serving Tray', 'A beautiful and functional serving tray made from sustainable hardwood', 39.99, 50),
('Fitness Resistance Bands', 'A set of high-quality resistance bands for strength training and physical therapy', 29.99, 100),
('Handmade Ceramic Mug', 'A unique and beautiful mug handmade by a local artist', 24.99, 50),
('Air Purifier', 'A powerful air purifier that removes allergens, dust, and other pollutants from your home', 149.99, 30),
('Digital Kitchen Scale', 'A precise and easy-to-use kitchen scale for measuring ingredients', 19.99, 100),
('Waterproof Hiking Boots', 'A durable and comfortable pair of hiking boots for outdoor adventures', 129.99, 40),
('Bluetooth Headphones', 'Wireless headphones with high-quality sound and noise-cancelling technology', 99.99, 75),
('Reusable Silicone Food Bags', 'Eco-friendly and durable food storage bags made from silicone', 14.99, 150);