INSERT INTO Product (name, description, price, stock) VALUES
('Compostable Phone Grip', 'Biodegradable grip accessory for smartphones with secure hold', 7.49, 120),
('Merino Wool Beanie', 'Warm knitted beanie made with soft merino wool blend', 22.95, 60),
('USB-C Fast Charge Cable', 'Durable braided USB-C cable supporting fast charging and data', 9.99, 240),
('Ceramic Pour-Over Dripper', 'Stoneware dripper for consistent pour-over coffee brewing', 18.50, 80),
('Insulated Lunch Box', 'Leak-proof lunch box with thermal lining for hot or cold meals', 29.75, 90),
('Ergonomic Mouse Pad', 'Gel wrist support mouse pad for comfortable desk work', 11.20, 150),
('Refillable Fountain Pen', 'Metal-bodied pen with converter for bottled ink refills', 16.40, 110),
('Plant-Based Protein Bar Pack', 'Assorted protein bars made from plant ingredients, box of 12', 19.80, 200),
('Noise-Reducing Earplugs', 'Reusable silicone earplugs designed to reduce ambient noise', 12.60, 170),
('Compact First Aid Kit', 'Pocket-sized first aid kit with essentials for minor injuries', 14.35, 140),
('Microfibre Cleaning Cloths', 'Lint-free cloth set for screens, glass, and stainless surfaces', 8.90, 300),
('Adjustable Laptop Stand', 'Aluminum stand with height and angle adjustment for laptops', 27.30, 75),
('Glass Meal Prep Containers', 'Set of 3 airtight glass containers for meal prep and storage', 34.99, 65),
('Rechargeable Bike Light', 'USB rechargeable front bike light with multiple brightness modes', 21.15, 95),
('Stainless Steel Straw Set', 'Set of 8 steel straws with cleaning brushes and pouch', 13.25, 180),
('Travel Packing Cubes', 'Set of 6 packing cubes to organize luggage efficiently', 24.40, 85),
('Cast-Iron Skillet 10in', 'Pre-seasoned cast-iron skillet for stove and oven cooking', 39.50, 40),
('Natural Deodorant Stick', 'Aluminum-free deodorant with natural botanical fragrance', 10.95, 160),
('E-reader Sleeve Case', 'Padded sleeve to protect e-readers during travel', 17.60, 105),
('Herbal Tea Sampler', 'Selection of caffeine-free herbal teas, 20 sachets', 15.75, 130),
('Magnetic Whiteboard Set', 'Dry-erase whiteboard with magnets, markers, and eraser', 26.80, 70),
('Weatherproof Notebook', 'Water-resistant notebook for outdoor notes and fieldwork', 6.99, 220),
('Cordless Mini Vacuum', 'Handheld cordless vacuum for quick car and desk cleanups', 33.45, 55),
('Yoga Cork Block', 'High-density cork yoga block for stability in poses', 12.25, 190);